api/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from api import views
from rest_framework.urlpatterns import format_suffix_patterns

router = routers.DefaultRouter()
# router.register(r'(?P<pr_id>[0-9]+)/news', views.ProjectNewsViewSet.as_view())
router.register(r'sourcefull', views.SourceFullViewSet)
router.register(r'smitype', views.SmiTypeViewSet)
# router.register(r'^project/status/create$', views.StatusCreate)
# router.register(r'sourcefull-detail', views.SourceFullDetail)

urlpatterns = [
    # url(r'^', include(router.urls)),
    # Новости

    url(r'^news/(?P<pk>[0-9]+)/$', views.ProjectNewsMinDetail.as_view()),
    url(r'^news/detail/(?P<pk>[0-9]+)/$', views.ProjectNewsDetail.as_view()),
    url(r'^news/detail/analytics/num/(?P<pk>[0-9]+)/$', views.ParamNumPNews.as_view()),
    url(r'^news/detail/analytics/list/(?P<pk>[0-9]+)/$', views.ParamListPNews.as_view()),
    # url(r'^news/detail/analytics/bool/(?P<pk>[0-9]+)/$', views.ProjectNewsDetail.as_view()),
    url(r'^news/update/(?P<pk>[0-9]+)/$', views.ProjectNewsUpdate.as_view()),
    url(r'^news/min/update/$', views.ProjectNewsMinUpdate.as_view()),
    url(r'^news/ptr/copy/$', views.ProjectNewsPTRCopy.as_view()),
    url(r'^news/ptr/move/$', views.ProjectNewsPTRMove.as_view()),
    url(r'^news/delete/$', views.ProjectNewsDelete.as_view()),
    url(r'^news/create/$', views.ProjectNewsCreate.as_view()),
    url(r'^news/add/param/num/$', views.ProjectNewsAddParamNum.as_view()),
    url(r'^news/add/param/bool/$', views.ProjectNewsAddParamBool.as_view()),
    url(r'^news/add/param/list/$', views.ProjectNewsAddParamList.as_view()),
    url(r'^news/highlight/(?P<n_pk>[0-9]+)/(?P<q_pk>[0-9]+)/$', views.NewsHighlight.as_view()),


    # Статусы
    url(r'^project/(?P<pr_id>[0-9]+)/statuses/$', views.StatusList.as_view()),
    url(r'^project/status/create/$', views.StatusCreate.as_view()),
    url(r'^project/status/update/$', views.StatusUpdate.as_view()),
    url(r'^project/status/delete/$', views.StatusDelete.as_view()),
    # Тональность
    url(r'^project/(?P<pr_id>[0-9]+)/tonalities/$', views.TonalityList.as_view()),
    url(r'^project/tonality/create/$', views.TonalityCreate.as_view()),
    url(r'^project/tonality/update/$', views.TonalityUpdate.as_view()),
    url(r'^project/tonality/delete/$', views.TonalityDelete.as_view()),
    # url(r'^project/tonality/delete/$', views.TonalityDelete.as_view()),

    # Источники
    url(r'^source/all/$', views.SourceFullList.as_view()),
    # Проекты
    url(r'^project/all/$', views.ProjectList.as_view()),
    url(r'^project/(?P<pr_id>[0-9]+)/news/$', views.ProjectNewsList.as_view()),
    url(r'^project/news/add/$', views.News_PTR.as_view()),
    # Темы
    url(r'^project/(?P<pr_id>[0-9]+)/theme/all/$', views.ThemeList.as_view()),
    # Рубрики
    url(r'^theme/(?P<t_id>[0-9]+)/rubric/all/$', views.RubricList.as_view()),
    # Аналитики
    # Числовые
    url(r'^project/(?P<pr_id>[0-9]+)/analytics/num/$', views.AnalyticNumList.as_view()),
    # Булевы
    url(r'^project/(?P<pr_id>[0-9]+)/analytics/bool/$', views.AnalyticBoolList.as_view()),
    url(r'^analytic/bool/(?P<a_id>[0-9]+)/params/$', views.ParamBoolList.as_view()),
    # Списочные
    url(r'^project/(?P<pr_id>[0-9]+)/analytics/list/$', views.AnalyticListList.as_view()),
    url(r'^analytic/list/(?P<a_id>[0-9]+)/params/$', views.ParamListList.as_view()),

    # Запросы

    url(r'^query/news/all/(?P<id>[0-9]+)/$', views.NewsList.as_view(), {'type': 'all'}),
    url(r'^query/news/in/(?P<id>[0-9]+)/$', views.NewsList.as_view(), {'type': 'in'}),
    url(r'^query/news/view/(?P<id>[0-9]+)/$', views.NewsList.as_view(), {'type': 'view'}),
    url(r'^query/news/del/(?P<id>[0-9]+)/$', views.NewsList.as_view(), {'type': 'del'}),
    url(r'^query/news/app/(?P<id>[0-9]+)/$', views.NewsList.as_view(), {'type': 'app'}),
    url(r'^query/news/modify/in/(?P<id>[0-9]+)/$', views.NewsModify.as_view(), {'type': 'in'}),
    url(r'^query/news/modify/view/(?P<id>[0-9]+)/$', views.NewsModify.as_view(), {'type': 'view'}),
    url(r'^query/news/modify/del/(?P<id>[0-9]+)/$', views.NewsModify.as_view(), {'type': 'del'}),
    url(r'^query/news/modify/app/(?P<id>[0-9]+)/$', views.NewsModify.as_view(), {'type': 'app'}),

    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

search/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.admin.views.decorators import staff_member_required

from search.views import *

urlpatterns = [

                  url(r'^$', search, name='search'),

                  # ListViews
                  url(r'^searchquery_list/$', staff_member_required(SearchQueryListView.as_view()),
                      name='searchquery_list'),

                  # CreateViews
                  url(r'^searchquery_form/$', staff_member_required(SearchQueryCreateView.as_view()),
                      name='searchquery_form'),

                  # DetailViews
                  url(r'^news_detail/(?P<pk>[0-9]+)$', staff_member_required(NewsDetailView.as_view()),
                      name='news_detail'),

                  # Update
                  url(r'^searchquery_update/(?P<pk>[0-9]+)/$', staff_member_required(SearchQueryUpdateView.as_view()),
                      name='searchquery_update'),

                  # Delete
                  url(r'^searchquery_delete/(?P<pk>[0-9]+)/$', staff_member_required(searchquery_delete),
                      name='searchquery_delete'),

                  # Helpers
                  url(r'^simple_search_query_form/$', staff_member_required(simple_search_query_form),
                      name='simple_search_query_form'),
                  # показать все найденные новости по сохраненному запросу
                  url(r'^saved_search_all_news/(?P<pk>[0-9]+)/$', staff_member_required(saved_search_all_news),
                      name='saved_search_all_news'),
                  # показать все не обработанные новости inbox
                  url(r'^saved_search_in_news/(?P<pk>[0-9]+)/$', staff_member_required(saved_search_in_news),
                      name='saved_search_in_news'),
                  # показать все просмотренные новости
                  url(r'^saved_search_viewed_news/(?P<pk>[0-9]+)/$', staff_member_required(saved_search_viewed_news),
                      name='saved_search_viewed_news'),
                  # показать все удаленные новости
                  url(r'^saved_search_deleted_news/(?P<pk>[0-9]+)/$', staff_member_required(saved_search_deleted_news),
                      name='saved_search_deleted_news'),
                  # показать все Одобренные новости
                  url(r'^saved_search_approved_news/(?P<pk>[0-9]+)/$',
                      staff_member_required(saved_search_approved_news),
                      name='saved_search_approved_news'),

                  # todo После переноса действий над объектами из вьюшки в модели , посмотреть можно ли сюда запихать
                  # эти методы без перехода во вьюшку'

                  # Пометить новость как прочитанную
                  url(r'^saved_search_mark_read_one/(?P<ss_id>[0-9]+)/(?P<news_id>[0-9]+)/$',
                      staff_member_required(saved_search_mark_read_one),
                      name='saved_search_mark_read_one'),
                  # Переместить новость в карзину
                  url(r'^saved_search_del_news_one/(?P<ss_id>[0-9]+)/(?P<news_id>[0-9]+)/$',
                      staff_member_required(saved_search_del_news_one),
                      name='saved_search_del_news_one'),
                  # Пометить новость как одобренную
                  url(r'^saved_search_approve_news_one/(?P<ss_id>[0-9]+)/(?P<news_id>[0-9]+)/$',
                      staff_member_required(saved_search_approve_news_one),
                      name='saved_search_approve_news_one'),

                  # простой отчет DOCX
                  url(r'^export_doc_simple/(?P<pk>[0-9]+)/$', staff_member_required(export_doc_simple),
                      name='export_doc_simple'),
                  # простой отчет HTML
                  url(r'^export_html_simple/(?P<pk>[0-9]+)/$', staff_member_required(export_html_simple),
                      name='export_html_simple'),
                  # простой отчет HTML для категории ALL
                  url(r'^export_html_simple_all/(?P<pk>[0-9]+)/$', staff_member_required(export_html_simple_all),
                      name='export_html_simple_all'),
                  # простой отчет HTML групповой
                  url(r'^export_html_simple_group/$', staff_member_required(export_html_simple_group),
                      name='export_html_simple_group'),

                  # url(r'^news_found_list/$', staff_member_required(news_found_list),
                  #     name='news_found_list'),
                  url(r'^close$', close, name='close'),
                  url(r'^make_xml/$', xml_news),


              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

smimonitor/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^catalog/', include('catalog.urls')),
    url(r'^search/', include('search.urls')),
    url(r'^projects/', include('projects.urls')),
    url(r'^api/', include('api.urls')),

    url(r'^', include('crowler.urls')),

    # url(r'^scheduler/', include('scheduler.urls'))
]
# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

crowler/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from collections import Counter


# Create your models here.


class Source(models.Model):
    name = models.CharField(verbose_name='Название источника', max_length=150)
    url = models.URLField(verbose_name='Начальная ссылка')
    code = models.DecimalField(verbose_name='Числовой код', max_digits=4, decimal_places=0, blank=True, unique=True, null=True)

    def last_news(self):
        return self.news_set.latest(field_name='date_post')

    def time_without_news(self):
        return timezone.datetime.now() - self.last_news()

    def chart_data(self):
        # todo сделать с параметрами, что бы отдавала данные по заданным датам
        time = timezone.datetime.strptime('00:00:00 +0300', '%H:%M:%S %z')
        day = timezone.timedelta(days=1)
        now = timezone.datetime.now() - day * 10
        now = timezone.datetime.combine(now, time.time()).replace(tzinfo=time.tzinfo)
        n = list(self.news_set.all().filter(date_post__gte=now.date()).values_list('date_post', flat=True))
        # n = self.news_set.all().filter(date_post__gte=now.date())
        # days = n.dates('date_post', 'day')
        # charts = []
        n = tuple(map(lambda x: timezone.datetime.combine(x, time.time()).replace(tzinfo=time.tzinfo).strftime('%Y-%m-%d'), n))
        c = Counter()
        for i in n:
            c[i] += 1
        # for i in days:
        #     d = timezone.datetime.combine(i, time.time()).replace(tzinfo=time.tzinfo)
        #     c = n.filter(date_post__range=[d, d + day]).values_list('id', flat=True)
        #     charts.append({'day': d, 'count': len(c)})
        return dict(c)

    class Meta:
        verbose_name = 'Источник'
        verbose_name_plural = 'Источники'

    def __str__(self):
        return self.name


class News(models.Model):
    url = models.URLField(unique=True)
    title = models.TextField(blank=True, null=True)
    text = models.TextField(blank=True, null=True)
    date_post = models.DateTimeField(db_index=True, blank=True, null=True)
    date_add = models.DateTimeField(auto_now_add=True)
    source = models.ForeignKey(Source, verbose_name='Источник', blank=True, null=True, default=None)
    unloaded = models.ManyToManyField(User, editable=False, blank=True, default=None)

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'

    def __str__(self):
        s = 'Нет текста новости'
        try:
            s = self.title[:20] + '...'
        except TypeError as e:
            print(e)
        return s

search/forms.py
from django import forms
from catalog.models import SourceQuery
from search.models import SearchQuery
import datetime
from django.utils import timezone


class SimpleSearchForm(forms.Form):
    query_string = forms.CharField(widget=forms.TextInput(attrs={'size': '120'}), )
    date_start = forms.DateField(required=False, label='C',
                                 widget=forms.SelectDateWidget(
                                     years=range(datetime.date.today().year - 5, datetime.date.today().year + 1)
                                 ),
                                 initial=timezone.datetime.today().date() - timezone.timedelta(days=3))
    date_end = forms.DateField(required=False, label='По',
                               widget=forms.SelectDateWidget(
                                   years=range(datetime.date.today().year - 5, datetime.date.today().year + 1)
                               ),
                               initial=timezone.datetime.today().date()
                               )
    sources = forms.ModelMultipleChoiceField(required=False, label='Запросы по источникам', queryset=SourceQuery.objects.all())


class SavedSearchQueryGroupReportForm(forms.Form):
    saved_search_queries = forms.ModelMultipleChoiceField(required=False, label='Сохраненные запросы', queryset=SearchQuery.objects.all(), widget=forms.CheckboxSelectMultiple())

search/templates/search/news_found_list.html
{% block news_list %}
    {% load search_extras %}
    {#    <div align="center">#}
    <div align="center">
        <h3>Найденные новости</h3>
        Найдено: {{ total }} показано {{ news_list.count }}
    </div>


    <table id="data-table" class="table table-responsive">
        <thead>
        <tr>
            <th>id</th>
            <th>Выгружено</th>
            <th>Источник</th>
            <th>Заголовок</th>
            <th>Дата публикации</th>
        </tr>
        </thead>
        <tbody>
        {% for news in news_list %}
            <tr id="row_{{ news.id }}">
                <td>{{ news.id }}</td>
                {% if request.user in news.unloaded %}
                    <td>Да</td>
                {% else %}
                    <td>Нет</td>

                {% endif %}
                <td>{{ news.source.name }}</td>
                <td>
                    <a href="#" data-toggle="modal" data-target="#modal_{{ news.id }}">
                        {{ news.title }}
                    </a>
                </td>
                <td class="td-small">{{ news.date_post|date:"Y/m/d-H:m" }}</td>

            </tr>

        {% endfor %}


        </tbody>
    </table>
    {#    </div>#}
    {% for news in news_list %}
        <div id="modal_{{ news.id }}" class="col-lg-12 modal fade">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><i class="fa fa-info-circle fa-fw"></i></h3>
                </div>
                <div class="panel-body">
                    <div align="center">

                        <button type="button" class="btn-sm btn-danger" data-dismiss="modal">
                            Закрыть
                        </button>
                    </div>

                    <h3>Подробно</h3>
                    <h4>{{ news.source.name }}</h4>
                    Дата публикации {{ news.date_post }}
                    Дата добавления в базу {{ news.date_add }}
                    {% autoescape off %}
                        <h3>{% replace_highlight news.title highlights_title|get_dict_value:news.id %}</h3>
                        <p>{% replace_highlight news.text highlights_text|get_dict_value:news.id %}</p>
                    {% endautoescape %}
                    <p>Ссылка на источник <a href="{{ news.url }}">{{ news.url }}</a></p>

                </div>

            </div>
        </div>


    {% endfor %}


    <script>
        $('#data-table').DataTable(
            {
                scrollY: '50vh',
                scrollCollapse: true,
                paging: false
            }
        );

    </script>

{% endblock %}

search/templates/search/news_found_list_marks.html
{#{% extends 'search/debug.html' %}#}
{% block news_found_list_mark %}
    {% load search_extras %}


    {#  <form action="" method="post" enctype="multipart/form-data">#}
    <div align="center"><h4>Групповая обработка новостей</h4></div>
    <div class="panel-success">
        <div class="panel-heading">
            <a data-toggle="collapse" href="#add_news">Перемещение в проекты\темы\рубрики</a>
        </div>
        <div id="add_news" class="panel-collapse collapse">
            <div class="panel-body">
                <form>
                    {% csrf_token %}
                    <div class="row">
                        <div id="projects_l_" class="col-md-3">
                            <label for="#project_s_">Проект:</label>
                            <select name="project" id="project_s_" onchange=load_themes('')></select>
                        </div>
                        <div id="themes_l_" class="col-md-3" hidden>
                            <label for="#theme_s_">Тема:</label>
                            <select name="theme" id="theme_s_" onchange="load_rubrics('')"></select>
                        </div>
                        <div id="rubrics_l_" class="col-md-3" hidden>
                            <label for="#rubric_s_">Рубрика:</label>
                            <select name="rubric" id="rubric_s_"></select>
                        </div>
                        <div class="col-md-3">
                            {#                        <button class="btn btn-danger btn-xs" onclick="add_news('', '#saved_search_result')">#}
                            <button class="btn btn-danger btn-xs js-add-news-ptr">
                                Прикрепить
                            </button>
                        </div>
                    </div>
                </form>

            </div>
        </div>
        <script>
            load_projects('');
            $('.js-add-news-ptr').on('click', function () {
                event.preventDefault();
                var f = $(this).closest('form');
                var d = f.serializeObject();
                var table = window['dt'];
                var rows = table.rows('.selected');
                var news_ids = rows.ids().toArray();
                d.news = news_ids;
                return $.ajax({
                    dataType: "json",
                    url: "/api/query/add_ptr/",
                    type: "put",
                    data: d,
                    error: function (data) {
                        alert('Ошибка добавления новостей \n Ошибка: ' + data.responseJSON.detail)
                    },
                    beforeSend: function (xhr) {
                        xhr.setRequestHeader('X-CSRFToken', d.csrfmiddlewaretoken)
                    },
                    success: function (data) {
                        console.log(data);
                        rows.remove().draw();
                        table_to.rows.add(data).draw();
                        alert('Новость сохранена');
                    }
                })
            });
        </script>
    </div>

    <div align="center">
        <h4>Найденные новости</h4>
        Наименование запроса:<strong>"{{ query.name }}"</strong> /
        Найдено: {{ total }} показано {{ news_list.count }}
    </div>


    <table id="data-table" class="table table-responsive">
        <thead>
        <tr>
            {#            <th><i class="fa fa-check-square-o" aria-hidden="true"></i></th>#}
            <th>id</th>
            <th>Статус</th>
            <th>Источник</th>
            <th>Заголовок</th>
            <th>Дата публикации</th>
            <th>Действия</th>
        </tr>
        </thead>
        <tbody>
        {% with view_ids as viewed_news %}
            {% with del_ids as deleted_news %}
                {% with app_ids as approved_news %}

                    {% for news in news_list %}
                        <tr
                                {% if news.id in deleted_news %}
                                    class="tr-red"
                                {% elif news.id in approved_news %}
                                    class="tr-green"
                                {% elif news.id in viewed_news %}
                                    class="tr-grey"
                                {% else %}
                                    class="tr-blue"
                                {% endif %}
                                    id="row_{{ news.id }}">
                            {#                            <td><input id="news_{{ news.id }}" name="news_{{ news.id }}" type="checkbox"#}
                            {#                                       value={{ news.id }}></td>#}
                            <td>{{ news.id }}</td>
                            <td>
                                {% if news.id in deleted_news %}
                                    DELETED
                                {% elif news.id in approved_news %}
                                    APPROVED
                                {% elif news.id in viewed_news %}
                                    VIEWED
                                {% else %}
                                    NEW
                                {% endif %}
                            </td>

                            <td>{{ news.source__name }}</td>
                            <td>
                                <a href="#" data-toggle="modal" data-target="#modal_{{ news.id }}"
                                   onclick="saved_search_mark_read_one('saved_search_mark_read_one/{{ query.id }}/{{ news.id }}','#row_{{ news.id }}')">
                                    {{ news.title }}

                                </a>
                            </td>
                            <td class="td-small">{{ news.date_post|date:"Y/m/d-H:i" }}</td>
                            <td>
                                <div class="btn-group" style="display: flex">
                                    <button type="button" class="btn btn-xs btn-danger"
                                            onclick="del_object('saved_search_del_news_one/{{ query.id }}/{{ news.id }}','#row_{{ news.id }}')">
                                        Удалить
                                    </button>
                                    <button type="button" class="btn btn-xs btn-success"
                                            onclick="saved_search_approve_news_one('saved_search_approve_news_one/{{ query.id }}/{{ news.id }}','#row_{{ news.id }}')">
                                        Оставить
                                    </button>
                                    <div class="btn-group btn-group-left">
                                        <button type="button" class="btn btn-xs btn-warning dropdown-toggle"
                                                data-toggle="dropdown">
                                            В проект <span class="caret"></span></button>
                                        <ul class="dropdown-menu" style="left: -15em" role="menu">
                                            <li><a href="#">В разработке</a></li>
                                            <li><a href="#">Будут показаны первые 40 символов .......</a></li>
                                            <li><a href="#">названия проекта</a></li>
                                        </ul>
                                    </div>

                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                {% endwith %}
            {% endwith %}
        {% endwith %}
        </tbody>
    </table>
    {#    </div>#}
    {% for news in news_list %}
        <div id="modal_{{ news.id }}" class="col-lg-12 modal fade">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><i class="fa fa-info-circle fa-fw"></i></h3>
                </div>
                <div class="panel-body">
                    <div align="center">
                        <button type="button" class="btn-sm btn-danger" data-dismiss="modal">
                            Закрыть
                        </button>
                    </div>
                    <h3>Подробно</h3>
                    <h4>{{ news.source__name }}</h4>
                    Дата публикации {{ news.date_post }}
                    Дата добавления в базу {{ news.date_add }}
                    {% autoescape off %}
                        <h3>{% replace_highlight news.title highlights_title|get_dict_value:news.id %}</h3>
                        <p>{% replace_highlight news.text highlights_text|get_dict_value:news.id %}</p>
                    {% endautoescape %}
                    <p>Ссылка на источник <a href="{{ news.url }}">{{ news.url }}</a></p>
                </div>
            </div>
        </div>


    {% endfor %}


    <script>
        var dt = $('#data-table').DataTable(
            {
                scrollY: '70vh',
                scrollCollapse: true,
                paging: false,
                rowId: 'id',
                dom: 'Bfrtip',
                buttons: {
                    buttons: [
                        'selectAll',
                        'selectNone',
                        'excel',
                        'pdf',
                        'csv',
                        'columnsToggle'
                    ]
                },
                columnDefs: [
                    {width: '75px', targets: 0},
                    {width: '75px', targets: 1},
                    {width: '120px', targets: 2},
                    {width: '400px', targets: 3},
                    {width: '75px', targets: 4}
                ],
                {#                fnRowCallback: function (row, data, dataIndex) {#}
                {#                    if (data.status) {#}
                {#                        var r = $('tr', row);#}
                {#                        console.log(r);#}
                {#                    }#}
                {#                },#}
{#                columns: {}#}
            }
        );


        $('#data-table tbody').on('click', 'tr[role="row"]', function () {
            $(this).toggleClass('selected');
        });
    </script>

{% endblock %}

search/templates/search/saved_search_query_group_report_form.html
{% block saved_search_query_group_report_form %}
    <div align="center">
    <h3>Груповой отчет</h3>
    <div align="center">Отметьте нужные запросы</div>
    </div>
    <form id="saved_search_query_group_report_form" action="{% url 'export_html_simple_group' %}"  target="_blank" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_table }}
        <input type="submit" class="btn btn-danger btn-xs" value="Отправить"/>
    </form>
{#    <script>#}
{#        $('#saved_search_query_group_report_form').submit(function (event) {#}
{#            $.post('{% url 'export_html_simple_group' %}', $("#saved_search_query_group_report_form").serialize(), function (data) {#}
{#                $("#search_result").html(data);#}
{#            }#}
{#            );#}
{#            return false;#}
{#        });#}
{#    </script>#}

{% endblock %}

search/templates/search/searchquery_form.html
{% block searchquery_form %}
    <button type="button" class="btn-sm btn-danger" data-dismiss="modal">Закрыть</button>
    <div align="center">
    <h3>Добавление запроса по новостям</h3>
    </div>
    <form id="form" action="{% url 'searchquery_form' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Сохранить"/>
    </form>


{% endblock %}

search/templates/search/simple_search_query_form.html
{% block simple_search_query_form %}
    <div align="center">
    <h3>Простой запрос</h3>
    <div align="center">Здесь можно тестировать запросы, выводится первые <strong>1000</strong> совпадений</div>
    </div>
    <form id="simple_search_query_form" action=""  method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-danger btn-xs" value="Отправить"/>
    </form>
    <script>
        $('#simple_search_query_form').submit(function (event) {
            $.post('{% url 'simple_search_query_form' %}', $("#simple_search_query_form").serialize(), function (data) {
                $("#search_result").html(data);
            });
            return false;
        });
    </script>

{% endblock %}

search/templates/search/update_form.html
{% block update_form %}
    <div align="center">
    <h3>Изменение обЪекта</h3>
    </div>
    <form id="form" action="" method="post" enctype="multipart/form-data" >
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Сохранить"/>
    </form>
{% endblock %}