api/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from api import views
from rest_framework.urlpatterns import format_suffix_patterns

router = routers.DefaultRouter()
# router.register(r'(?P<pr_id>[0-9]+)/news', views.ProjectNewsViewSet.as_view())
router.register(r'sourcefull', views.SourceFullViewSet)
router.register(r'smitype', views.SmiTypeViewSet)
# router.register(r'^project/status/create$', views.StatusCreate)
# router.register(r'sourcefull-detail', views.SourceFullDetail)

urlpatterns = [
    # url(r'^', include(router.urls)),
    # Новости

    url(r'^news/(?P<pk>[0-9]+)/$', views.ProjectNewsMinDetail.as_view()),
    url(r'^news/detail/(?P<pk>[0-9]+)/$', views.ProjectNewsDetail.as_view()),
    url(r'^news/detail/analytics/num/(?P<pk>[0-9]+)/$', views.ParamNumPNews.as_view()),
    url(r'^news/detail/analytics/list/(?P<pk>[0-9]+)/$', views.ParamListPNews.as_view()),
    # url(r'^news/detail/analytics/bool/(?P<pk>[0-9]+)/$', views.ProjectNewsDetail.as_view()),
    url(r'^news/update/(?P<pk>[0-9]+)/$', views.ProjectNewsUpdate.as_view()),
    url(r'^news/min/update/$', views.ProjectNewsMinUpdate.as_view()),
    url(r'^news/ptr/copy/$', views.ProjectNewsPTRCopy.as_view()),
    url(r'^news/ptr/move/$', views.ProjectNewsPTRMove.as_view()),
    url(r'^news/delete/$', views.ProjectNewsDelete.as_view()),
    url(r'^news/create/$', views.ProjectNewsCreate.as_view()),
    url(r'^news/add/param/num/$', views.ProjectNewsAddParamNum.as_view()),
    url(r'^news/add/param/bool/$', views.ProjectNewsAddParamBool.as_view()),
    url(r'^news/add/param/list/$', views.ProjectNewsAddParamList.as_view()),
    url(r'^news/highlight/(?P<n_pk>[0-9]+)/(?P<q_pk>[0-9]+)/$', views.NewsHighlight.as_view()),


    # Статусы
    url(r'^project/(?P<pr_id>[0-9]+)/statuses/$', views.StatusList.as_view()),
    url(r'^project/status/create/$', views.StatusCreate.as_view()),
    url(r'^project/status/update/$', views.StatusUpdate.as_view()),
    url(r'^project/status/delete/$', views.StatusDelete.as_view()),
    # Тональность
    url(r'^project/(?P<pr_id>[0-9]+)/tonalities/$', views.TonalityList.as_view()),
    url(r'^project/tonality/create/$', views.TonalityCreate.as_view()),
    url(r'^project/tonality/update/$', views.TonalityUpdate.as_view()),
    url(r'^project/tonality/delete/$', views.TonalityDelete.as_view()),
    # url(r'^project/tonality/delete/$', views.TonalityDelete.as_view()),

    # Источники
    url(r'^source/all/$', views.SourceFullList.as_view()),
    # Проекты
    url(r'^project/all/$', views.ProjectList.as_view()),
    url(r'^project/(?P<pr_id>[0-9]+)/news/$', views.ProjectNewsList.as_view()),
    url(r'^project/news/add/$', views.News_PTR.as_view()),
    # Темы
    url(r'^project/(?P<pr_id>[0-9]+)/theme/all/$', views.ThemeList.as_view()),
    # Рубрики
    url(r'^theme/(?P<t_id>[0-9]+)/rubric/all/$', views.RubricList.as_view()),
    # Аналитики
    # Числовые
    url(r'^project/(?P<pr_id>[0-9]+)/analytics/num/$', views.AnalyticNumList.as_view()),
    # Булевы
    url(r'^project/(?P<pr_id>[0-9]+)/analytics/bool/$', views.AnalyticBoolList.as_view()),
    url(r'^analytic/bool/(?P<a_id>[0-9]+)/params/$', views.ParamBoolList.as_view()),
    # Списочные
    url(r'^project/(?P<pr_id>[0-9]+)/analytics/list/$', views.AnalyticListList.as_view()),
    url(r'^analytic/list/(?P<a_id>[0-9]+)/params/$', views.ParamListList.as_view()),

    # Запросы

    url(r'^query/news/all/(?P<id>[0-9]+)/$', views.NewsList.as_view(), {'type': 'all'}),
    url(r'^query/news/in/(?P<id>[0-9]+)/$', views.NewsList.as_view(), {'type': 'in'}),
    url(r'^query/news/view/(?P<id>[0-9]+)/$', views.NewsList.as_view(), {'type': 'view'}),
    url(r'^query/news/del/(?P<id>[0-9]+)/$', views.NewsList.as_view(), {'type': 'del'}),
    url(r'^query/news/app/(?P<id>[0-9]+)/$', views.NewsList.as_view(), {'type': 'app'}),
    url(r'^query/news/modify/in/(?P<id>[0-9]+)/$', views.NewsModify.as_view(), {'type': 'in'}),
    url(r'^query/news/modify/view/(?P<id>[0-9]+)/$', views.NewsModify.as_view(), {'type': 'view'}),
    url(r'^query/news/modify/del/(?P<id>[0-9]+)/$', views.NewsModify.as_view(), {'type': 'del'}),
    url(r'^query/news/modify/app/(?P<id>[0-9]+)/$', views.NewsModify.as_view(), {'type': 'app'}),

    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

projects/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.admin.views.decorators import staff_member_required
from projects.views import *

urlpatterns = [

                  url(r'^$', staff_member_required(projects), name='projects'),
                  # Проекты
                  url(r'^add/$', staff_member_required(add_project), name='add'),
                  url(r'^get/$', staff_member_required(get_projects), name='get'),
                  # url(r'^get_one/(?P<pk>[0-9]+)$', staff_member_required(get_project), name='get_one'),
                  url(r'^del_one/(?P<pk>[0-9]+)$', staff_member_required(del_project)),
                  url(r'^(?P<pk>[0-9]+)/journal/$', staff_member_required(get_journal)),
                  url(r'^rename/$', staff_member_required(rename_project), name='rename_project'),

                  # Темы
                  url(r'^themes/add/$', staff_member_required(add_theme), name='add_theme'),
                  url(r'^themes/rename/$', staff_member_required(rename_theme), name='rename_theme'),
                  url(r'^(?P<pk>[0-9]+)/themes/get/$', staff_member_required(get_themes)),
                  url(r'^(?P<pk>[0-9]+)/themes_ids/$', staff_member_required(themes_ids)),
                  # url(r'^themes/get_one/(?P<pk>[0-9]+)$', staff_member_required(get_theme), name='get_one'),
                  url(r'^themes/del_one/(?P<pk>[0-9]+)$', staff_member_required(del_theme)),

                  # Рубрики
                  url(r'^rubric/add/$', staff_member_required(add_rubric), name='add_rubric'),
                  url(r'^rubric/rename/$', staff_member_required(rename_rubric), name='rename_rubric'),
                  url(r'^projects_ids/$', staff_member_required(projects_ids), name='projects_ids'),
                  url(r'^themes/(?P<pk>[0-9]+)/rubrics/get/$', staff_member_required(get_rubrics)),
                  url(r'^themes/(?P<pk>[0-9]+)/rubrics_ids/$', staff_member_required(rubrics_ids)),
                  url(r'^rubrics/del_one/(?P<pk>[0-9]+)$', staff_member_required(del_rubric)),

                  # Аналитики
                  # Числовая
                  url(r'^analytics/num/add/$', staff_member_required(add_num_analytics), name='add_num_analytics'),
                  url(r'^(?P<pk>[0-9]+)/analytics/num/get/$', staff_member_required(get_num_analytics),
                      name='get_num_analytics'),
                  url(r'^(?P<pk>[0-9]+)/analytics/num/ids/$', staff_member_required(num_analytics_ids),
                      name='num_analytics_ids'),
                  url(r'^num_analytics/del_one/(?P<pk>[0-9]+)$', staff_member_required(del_num_analytic)),
                  url(r'^num_analytics/rename/$', staff_member_required(rename_num_analytics),
                      name='rename_num_analytics'),
                  url(r'^num_analytics/rename/$', staff_member_required(rename_num_analytics),
                      name='rename_num_analytics'),
                  url(r'^analytics/num/(?P<pk>[0-9]+)/add_param/$', staff_member_required(add_param_num_analytics),
                      name='add_param_num_analytics'),
                  # todo заменить на ту что из новостей
                  url(r'^analytics/num/param/del_one/(?P<pk>[0-9]+)$', staff_member_required(del_param_num_analytics)),
                  url(r'^analytics/num/param/edit/$', staff_member_required(edit_param_num_analytics)),
                  url(r'^analytics/num/param/journal/$', staff_member_required(edit_param_num_analytics)),

                  # Булевы
                  url(r'^analytics/bool/(?P<pk>[0-9]+)/ids/$', staff_member_required(bool_analytics_ids)),
                  url(r'^analytics/bool/params/(?P<pk>[0-9]+)/ids/$', staff_member_required(bool_params_ids)),
                  url(r'^analytics/bool/add/$', staff_member_required(add_bool_analytics), name='add_bool_analytics'),
                  url(r'^(?P<pk>[0-9]+)/analytics/bool/get/$', staff_member_required(get_bool_analytics),
                      name='bool_params_ids'),
                  url(r'^analytics/bool/rename/$', staff_member_required(rename_bool_analytics),
                      name='rename_bool_analytics'),
                  url(r'^analytics/bool/positive/rename/$', staff_member_required(rename_bool_positive),
                      name='rename_bool_positive'),
                  url(r'^analytics/bool/negative/rename/$', staff_member_required(rename_bool_negative),
                      name='rename_bool_negative'),
                  url(r'^analytics/bool/del_one/(?P<pk>[0-9]+)$', staff_member_required(del_bool_analytic)),
                  url(r'^analytics/bool/param/add/true$', staff_member_required(add_bool_analytic_param_true)),
                  url(r'^analytics/bool/param/add/false$', staff_member_required(add_bool_analytic_param_false)),
                  url(r'^analytics/bool/param/change/true/(?P<n_id>[0-9]+)/(?P<b_id>[0-9]+)$',
                      staff_member_required(change_bool_analytic_param_true)),
                  url(r'^analytics/bool/param/change/false/(?P<n_id>[0-9]+)/(?P<b_id>[0-9]+)$',
                      staff_member_required(change_bool_analytic_param_false)),
                  url(r'^analytics/bool/param/del_one/(?P<n_id>[0-9]+)/(?P<b_id>[0-9]+)$',
                      staff_member_required(del_bool_analytic_param)),

                  # Списочные
                  url(r'^(?P<pk>[0-9]+)/analytics/list/get/$', staff_member_required(get_list_analytics)),
                  url(r'^analytics/list/(?P<pk>[0-9]+)/ids/$', staff_member_required(list_analytics_ids)),
                  url(r'^analytics/list/params/(?P<pk>[0-9]+)/ids/$', staff_member_required(list_params_ids)),
                  url(r'^analytics/list/add/$', staff_member_required(add_list_analytics)),
                  url(r'^analytics/list/del_one/(?P<pk>[0-9]+)$', staff_member_required(del_list_analytic)),
                  url(r'^analytics/list/rename/$', staff_member_required(rename_list_analytics)),
                  url(r'^analytics/list/param/add/$', staff_member_required(add_list_param)),
                  url(r'^analytics/list/param/del_one/(?P<pk>[0-9]+)$', staff_member_required(del_list_param)),
                  url(r'^analytics/list/param/rename/$', staff_member_required(rename_list_param)),
                  url(r'^analytics/list/param/news/add$', staff_member_required(add_list_analytic_param)),
                  url(r'^analytics/list/param/del_one/(?P<n_id>[0-9]+)/(?P<p_id>[0-9]+)$',
                      staff_member_required(del_list_analytic_param)),

                  # Журнал

                  # Новости
                  # создать
                  url(r'^news/create/$', staff_member_required(project_news_create)),
                  # get news
                  url(r'^news/(?P<pk>[0-9]+)/edit', staff_member_required(get_project_news_edit)),
                  url(r'^news/(?P<pk>[0-9]+)/get/detail/row$', staff_member_required(get_news_project_row)),
                  url(r'^news/annotation/save$', staff_member_required(news_annotation_save)),
                  url(r'^news/text/save$', staff_member_required(news_text_save)),
                  url(r'^news/param/num/add/one$', staff_member_required(news_num_add_one)),
                  url(r'^news/param/num/del/one/(?P<pk>[0-9]+)$', staff_member_required(del_param_num_analytics)),
                  url(r'^news/param/bool/add/true$', staff_member_required(news_bool_add_true)),
                  url(r'^news/param/bool/add/false$', staff_member_required(news_bool_add_false)),
                  url(r'^news/param/bool/del/one/(?P<n_id>[0-9]+)/(?P<b_id>[0-9]+)$',
                      staff_member_required(del_bool_analytic_param)),
                  url(r'^news/param/list/add/one$', staff_member_required(news_list_add_one)),
                  url(r'^news/param/list/del/one/(?P<n_id>[0-9]+)/(?P<p_id>[0-9]+)$',
                      staff_member_required(del_list_analytic_param)),

                  # add news
                  url(r'^(?P<pk>[0-9]+)/add_news$', staff_member_required(add_news_project)),
                  url(r'^themes/(?P<pk>[0-9]+)/add_news$', staff_member_required(add_news_themes)),
                  url(r'^rubrics/(?P<pk>[0-9]+)/add_news$', staff_member_required(add_news_rubrics)),

                  url(r'^themes/(?P<pk>[0-9]+)/rubrics_ids$', staff_member_required(rubrics_ids), name=''),

                  # ListViews
                  # url(r'^sourcefull_list/$', staff_member_required(SourceFullListView.as_view()),
                  #     name='sourcefull_list'),
                  #   Формы
                  url(r'^status/create/(?P<pr_id>[0-9]+)$', staff_member_required(get_status_form)),

                  url(r'^make_xml/$', xml_news),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

smimonitor/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^catalog/', include('catalog.urls')),
    url(r'^search/', include('search.urls')),
    url(r'^projects/', include('projects.urls')),
    url(r'^api/', include('api.urls')),

    url(r'^', include('crowler.urls')),

    # url(r'^scheduler/', include('scheduler.urls'))
]
# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

crowler/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from collections import Counter


# Create your models here.


class Source(models.Model):
    name = models.CharField(verbose_name='Название источника', max_length=150)
    url = models.URLField(verbose_name='Начальная ссылка')
    code = models.DecimalField(verbose_name='Числовой код', max_digits=4, decimal_places=0, blank=True, unique=True, null=True)

    def last_news(self):
        return self.news_set.latest(field_name='date_post')

    def time_without_news(self):
        return timezone.datetime.now() - self.last_news()

    def chart_data(self):
        # todo сделать с параметрами, что бы отдавала данные по заданным датам
        time = timezone.datetime.strptime('00:00:00 +0300', '%H:%M:%S %z')
        day = timezone.timedelta(days=1)
        now = timezone.datetime.now() - day * 10
        now = timezone.datetime.combine(now, time.time()).replace(tzinfo=time.tzinfo)
        n = list(self.news_set.all().filter(date_post__gte=now.date()).values_list('date_post', flat=True))
        # n = self.news_set.all().filter(date_post__gte=now.date())
        # days = n.dates('date_post', 'day')
        # charts = []
        n = tuple(map(lambda x: timezone.datetime.combine(x, time.time()).replace(tzinfo=time.tzinfo).strftime('%Y-%m-%d'), n))
        c = Counter()
        for i in n:
            c[i] += 1
        # for i in days:
        #     d = timezone.datetime.combine(i, time.time()).replace(tzinfo=time.tzinfo)
        #     c = n.filter(date_post__range=[d, d + day]).values_list('id', flat=True)
        #     charts.append({'day': d, 'count': len(c)})
        return dict(c)

    class Meta:
        verbose_name = 'Источник'
        verbose_name_plural = 'Источники'

    def __str__(self):
        return self.name


class News(models.Model):
    url = models.URLField(unique=True)
    title = models.TextField(blank=True, null=True)
    text = models.TextField(blank=True, null=True)
    date_post = models.DateTimeField(db_index=True, blank=True, null=True)
    date_add = models.DateTimeField(auto_now_add=True)
    source = models.ForeignKey(Source, verbose_name='Источник', blank=True, null=True, default=None)
    unloaded = models.ManyToManyField(User, editable=False, blank=True, default=None)

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'

    def __str__(self):
        s = 'Нет текста новости'
        try:
            s = self.title[:20] + '...'
        except TypeError as e:
            print(e)
        return s

projects/forms.py
from django import forms
from projects.models import *


class StatusForm(forms.Form):
    name = forms.CharField(max_length=50)
    color = forms.CharField(max_length=20)
    bold = forms.BooleanField(initial=False, required=False)
    editable = forms.BooleanField(initial=False, required=False)
    project = forms.IntegerField(widget=forms.HiddenInput())

projects/templates/projects/bool_analytics_detail.html
{% block bool_analytics_detail %}

    {% for an in analytics %}
        <div id="bool_analytic_panel_{{ an.id }}" class="panel panel-success">
            <div class="panel-heading">

                <div class="col-md-8">
                    <a data-toggle="collapse" id="analytic_bool_name_a_{{ an.id }}"
                       href="#bool_analytic_{{ an.id }}">{{ an.name }}</a>

                </div>
                <div align="right">
                    <button class="btn btn-danger btn-xs"
                            onclick="del_object('/projects/analytics/bool/del_one/{{ an.id }}', '#bool_analytic_panel_{{ an.id }}')">
                        Удалить
                    </button>
                </div>
            </div>

            <div id="bool_analytic_{{ an.id }}" class="panel-collapse collapse">
                <div class="panel-body">
                    <a href="#" onclick="renameBoolAnalytic({{ an.id }}, '#analytic_bool_name_a_{{ an.id }}')"><i
                            class="fa fa-pencil-square-o"
                            aria-hidden="true"></i>
                        Переименовать Аналитику</a>
                    <hr>
                    <div class="inline-group">
                        Условно позитивное:
                        <br>
                        <strong id="analytic_bool_positive_{{ an.id }}">
                            {{ an.name_positive }}
                        </strong>
                        <br>
                        <a href="#" onclick="renameBoolPositive({{ an.id }}, '#analytic_bool_positive_{{ an.id }}')">
                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                            Изменить
                        </a>
                    </div>
                    <hr>
                    Условно негативное:
                    <br>
                    <strong id="analytic_bool_negative_{{ an.id }}">
                        {{ an.name_negative }}
                    </strong>
                    <br>
                    <a href="#" onclick="renameBoolNegative({{ an.id }}, '#analytic_bool_negative_{{ an.id }}')">
                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                        Изменить
                    </a>
                </div>
            </div>
        </div>
    {% endfor %}

{% endblock %}

projects/templates/projects/form.html
{#{% extends 'crowler/index.html' %}#}
{% load staticfiles %}
<script src="{% static 'crowler/js/jquery.js' %}"></script>
{% block form %}
    <form action="/api/project/status/create/" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn-xs btn-danger" type="submit" value="Сохранить"/>
    </form>


    <script>
        $(document).ready(function () {
            $('#id_color').attr('type', 'color');
        })
    </script>
{% endblock %}

projects/templates/projects/list_analytics_detail.html
{% block list_analytics_detail %}

    {% for an in analytics %}
        <div id="list_analytic_panel_{{ an.id }}" class="panel panel-success">
            <div class="panel-heading">

                <div class="col-md-8">
                    <a data-toggle="collapse" id="analytic_list_name_a_{{ an.id }}"
                       href="#list_analytic_{{ an.id }}">{{ an.name }}</a>

                </div>
                <div align="right">
                    <button class="btn btn-danger btn-xs"
                            onclick="del_object('/projects/analytics/list/del_one/{{ an.id }}', '#list_analytic_panel_{{ an.id }}')">
                        Удалить
                    </button>
                </div>
            </div>

            <div id="list_analytic_{{ an.id }}" class="panel-collapse collapse">
                <div class="panel-body">
                    <a href="#" onclick="renameListAnalytic({{ an.id }}, '#analytic_list_name_a_{{ an.id }}')"><i
                            class="fa fa-pencil-square-o"
                            aria-hidden="true"></i>
                        Переименовать Аналитику</a>
                    <hr>
                    Список параметров(тэгов):
                    <table class="table-responsive table-bordered" id="list_params_{{ an.id }}" style="max-width: 100%">
                        <tr>
                            <td>
                                <a href="#"
                                   onclick="addListParam('#list_params_{{ an.id }}', {{ an.id }})">
                                    <i class="fa fa-plus" aria-hidden="true"></i>
                                    Добавить параметр
                                </a>
                            </td>
                        </tr>
                        {% for p in an.params.all %}
                            <tr id="list_param_{{ an.id }}_p_{{ p.id }}">
                                <td>
                                    <val id="list_param_val_{{ p.id }}">{{ p.name }}</val>
                                    <a href="#"
                                       onclick="del_object('/projects/analytics/list/param/del_one/{{ p.id }}', '#list_param_{{ an.id }}_p_{{ p.id }}')"
                                       title="удалить параметр">
                                        x
                                    </a>
                                    <a href="#" onclick="change_param_list({{ p.id }}, '#list_param_val_{{ p.id }}')"
                                       title="переименовать">
                                        <i class="fa fa-pencil-square" aria-hidden="true"
                                           title="изменить занчение аналитики на противоположную"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>


                </div>
            </div>
        </div>
    {% endfor %}

{% endblock %}

projects/templates/projects/project_news_row.html
{% block project_news_detail_row %}
    <div class="row" style="max-width: 1024px">
        <div class="col-md-8">
            <form>
                <input id="id_news" name="news" type="hidden" value="{{ news.id }}">
                <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
                <div class="col-md-12">
                    Заголовок:
                    <textarea id="id_title" style="width: inherit" name="title" rows="2">{{ news.title }}</textarea>
                </div>
                <div class="col-md-12">
                    Аннотация:
                    <textarea type="text" id="id_annotation" style="width: inherit" name="annotation" rows="2">{{ news.annotation }}</textarea>
                </div>
                <div class="col-md-12">
                    Текст:
                    <textarea type="text" id="id_text" style="width: inherit" name="text" rows="5">{{ news.text }}</textarea>
                </div>
                <div align="right">
                    <input type="submit" class="btn btn-xs btn-danger js-news-update-min" value="Сохранить">
                </div>
            </form>

        </div>
        <div class="col-md-4">
            <div class="panel panel-default ">
                <div class="panel-heading"><a class="collapse-a" href="#">Статус:</a></div>
                <div class="panel-collapse collapse">
                    <div class="panel-body">
                        <form>
                            <input id="id_news" name="news" type="hidden" value="{{ news.id }}">
                            <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">

                            {% for status in project.statuses.all %}
                                <div>
                                    <div class="col-md-10"><input type="radio" name="id_status" value="{{ status.id }}"
                                                                  {% if news.status.id == status.id %}checked{% endif %}
                                    >
                                        {{ status.name }}</div>
                                    <div class="col-md-2 small-text" style="background-color: {{ status.color }}"> *</div>
                                </div>
                            {% endfor %}
                            <div align="right">
                                <input type="submit" class="btn btn-xs btn-danger js-news-update-min" value="Сохранить">
                            </div>
                        </form>
                        <script>
                            $('.js-news-update-status').on('click', function () {
                                event.preventDefault();
                                var f = $(this).closest('form');
                                console.log(f.serializeObject());
                                var d = f.serializeObject();
                                return $.ajax({
                                    dataType: "json",
                                    url: "/api/news/min/update/",
                                    type: "put",
                                    data: d,
                                    error: function (data) {
                                        alert('Ошибка сохранения новости \n Ошибка: ' + data.responseJSON.detail)
                                    },
                                    beforeSend: function (xhr) {
                                        xhr.setRequestHeader('X-CSRFToken', d.csrfmiddlewaretoken)
                                    },
                                    success: function (data) {
                                        alert('Новость сохранена');
                                        console.log(data);
                                        {#                            todo обновить тайтл в таблице#}
                                        console.log(data)

                                    }
                                })

                            });
                        </script>
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading"><a class="collapse-a" href="#">Тональность:</a></div>
                <div class="panel-collapse collapse">
                    <div class="panel-body">
                        <form>
                            <input id="id_news" name="news" type="hidden" value="{{ news.id }}">
                            <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
                            {% for tonality in project.tonalities.all %}
                                <div>
                                    <div class="col-md-10"><input type="radio" name="id_tonality" value="{{ tonality.id }}"
                                            {% if news.tonality.id == tonality.id %}
                                                                  checked
                                            {% endif %}
                                    >
                                        {{ tonality.name }}
                                    </div>
                                    <div class="col-md-2 small-text" style="background-color: {{ tonality.color }}"> *</div>
                                </div>
                            {% endfor %}
                            <div align="right">
                                <input type="submit" class="btn btn-xs btn-danger js-news-update-min" value="Сохранить">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        $('.collapse-a').on('click', function (e) {
            e.preventDefault();
            var a = $(this);
{#            console.log(a);#}
            var body = a.closest('.panel-heading').next('.panel-collapse');
{#            console.log(body);#}
            body.collapse('toggle')
        });

        $('.js-news-update-min').on('click', function () {
            event.preventDefault();
            var f = $(this).closest('form');
            var d = f.serializeObject();
            return $.ajax({
                dataType: "json",
                url: "/api/news/min/update/",
                type: "put",
                data: d,
                error: function (data) {
                    alert('Ошибка сохранения новости \n Ошибка: ' + data.responseJSON.detail)
                },
                beforeSend: function (xhr) {
                    xhr.setRequestHeader('X-CSRFToken', d.csrfmiddlewaretoken)
                },
                success: function (data) {
                    alert('Новость сохранена');
                    var n_id = data.id;
                    var row = jt_{{ project.id }}.row('#' + n_id);
                    row.data(data);
                    var r = $('tr', '#' + data.id);
                    if (data.status) {
                        r.prevObject['0'].style.color = data.status.color;
                        if (data.status.bold) {
                            r.prevObject['0'].style.fontWeight = "bold";
                        }
                    }
                    if (data.tonality){
                        r.prevObject['0'].style.backgroundColor = data.tonality.color;
                    }
                }
            })
        });
    </script>
{% endblock %}